import img from "./assets/images/banner_sports.png";
import img2 from "./assets/images/banner_kabaddi.png";
import img3 from "./assets/images/banner_skyexchangeBlog.png";
import img4 from "./assets/images/banner_virtualsports.png";
import img5 from "./assets/images/banner_royalgaming.png";
import img6 from "./assets/images/banner_evo-half.png";
import img7 from "./assets/images/banner_ezugi-half.png";
import img8 from "./assets/images/banner_casino-half.png";
import img9 from "./assets/images/banner_blackjack-half.png";

const videoLink = "https://recklinesports.com/#/casino-video?id=3030";
const livebeatURL = "livebeat";

export const cards = [
  {
    id: 1,
    title: "Sports",
    image: img,
    buttonText: "Play Now",
    videoLink,
    livebeat: "cricket",
    live: [
      { name: "Cricket", id: 1, link: "Cricket.com", score: "10" },
      { name: "Soccer", id: 2, link: "Soccer.com", score: "4" },
      { name: "Tennis", id: 3, link: "Tennis.com", score: "15" },
    ],
  },
  {
    id: 2,
    title: "Kabaddi",
    image: img2,
    buttonText: "Play Now",
    videoLink,
    livebeat: "kabaddi",
  },
  {
    id: 3,
    title: "Instant Worli",
    image: img3,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 4,
    title: "Queen",
    image: img4,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 5,
    title: "Lucky7 B",
    image: img5,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 6,
    title: "20-20 Dragon Tiger",
    image: img6,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 31,
    title: "20-20 Dragon Tiger 2",
    image: img8,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 32,
    title: "20-20 Poker",
    image: img5,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 12,
    title: "20-20 Teenpatti",
    image: img3,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 21,
    title: "20-20 DTL",
    image: img3,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 3,
    title: "Instant Worli",
    image: img3,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 4,
    title: "Queen",
    image: img4,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 5,
    title: "Lucky7 B",
    image: img5,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 7,
    title: "Cricket Match 20-20",
    image: img7,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 8,
    title: "Teenpatti Open",
    image: img8,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 9,
    title: "Casino War",
    image: img9,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 10,
    title: "Super Over",
    image: img,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 11,
    title: "1 Day Dragon Tiger",
    image: img2,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 13,
    title: "Baccarat",
    image: img4,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 14,
    title: "One Day Poker",
    image: img5,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 15,
    title: "32 Card A",
    image: img6,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 16,
    title: "3 Card",
    image: img7,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 17,
    title: "Amar Akbar Anthony",
    image: img8,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 18,
    title: "Teenpatti Test",
    image: img9,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 19,
    title: "Worli Matka",
    image: img,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 20,
    title: "Casino Meter",
    image: img2,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 22,
    title: "Teenpatti Onday",
    image: img4,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 23,
    title: "Andar Bahar",
    image: img5,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 24,
    title: "Bollywood Casino",
    image: img6,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 25,
    title: "Andar Bahar 2",
    image: img7,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 26,
    title: "Poker 6 Player",
    image: img8,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 27,
    title: "32 Cards B",
    image: img9,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 28,
    title: "Race 20",
    image: img,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 33,
    title: "Lucky 7",
    image: img6,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
  {
    id: 34,
    title: "Baccarat 2",
    image: img9,
    buttonText: "Play Now",
    videoLink,
    livebeat: livebeatURL,
  },
];
